name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Jalankan setiap 6 jam

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Start Scan
        run: |
          bun install && bun run ./helper/proxyip.ts

      - name: Publish Result
        if: ${{ success() }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./*List.txt || true
          git add ./*List.json || true
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          else
            git commit -m "Update proxy list"
            git push
